import type { Metadata } from 'next';
import { ReactNode } from 'react';
import localFont from 'next/font/local';
import './globals.css';

// Custom fonts
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Meta data for SEO
export const metadata: Metadata = {
  title: 'My Awesome Website',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="My awesome website with dark mode" />
        <title>My Awesome Website</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black transition-all duration-300`}
      >
        {children}
      </body>
    </html>
  );
}
